---
output:
  html_document: 
    toc: false
    toc_float: false
title: "Michael Yeomans"
---

<link rel="stylesheet" href="styles.css" type="text/css">
```{css, echo=FALSE}
.wdk_content-pagetitle {
display:none;
}
```

***

<div style="font-size: 15px">
My research studies the choices people make in conversation, in the context of the the goals they are pursuing. For a discussion of the conversational goal framework, please see this (short!) review paper:

Yeomans, M., Schweitzer, M. & Brooks, A.W. (2022). [The Conversational Circumplex: Identifying, Prioritizing, and Pursuing Informational and Relational Motives in Conversation](http://www.mikeyeomans.info/papers/circumplex.pdf). Current Opinion in Psychology, 44, 293-302.

Additionally, my colleagues and I have written a (longer!) review paper dealing with the unique challenges of dealing with conversations as data:

Yeomans, M., Boland, K.F., Collins, H., Abi-Esber, N. & Brooks, A.W. (2023) [A Practical Guide to Conversation Research](http://www.mikeyeomans.info/papers/PGCR_yeomans.pdf). Advances in Methods & Practices in Psychological Science, in press.

***
<div style="font-size: 12px">

## How can we manage disagreement constructively?

Yeomans, M., Bendersky, C., Weingart, L.R. & Kim, Y. (2024). A Natural Language Processing Model for Conflict Expression in Conversation. Under Review

Minson, J., Yeomans, M., Collins, H., Dorison, C. (2024) [Conversational Receptiveness Transmits Between Parties And Brdges Ideological Conflict.](http://www.mikeyeomans.info/papers/receptiveness.pdf). Journal of Personality and Social Psychology, in press.

Yeomans, M. (2022). [The Straw Man Effect: Partisan Misrepresentation in Natural Language ](http://www.mikeyeomans.info/papers/straw_men.pdf). Group Processes & Intergroup Relations,  25(7), 1905-1924.

Yeomans, M., Minson, J., Collins, H., Chen, F. & Gino, F. (2020) [Conversational Receptiveness: Improving Engagement With Opposing Views](http://www.mikeyeomans.info/papers/receptiveness.pdf). Organizational Behavior and Human Decision Processes, 160, 131-148.

Jeong, M., Minson, J., Yeomans, M. & Gino, F. (2019). [Communicating Warmth in Distributive Negotiations is Surprisingly Counter-Productive](http://www.mikeyeomans.info/papers/communicating_warmth.pdf). Management Science, 65(12), 5449-5956.

Yeomans, M., Reich, J. Stewart, B., Kindel, A.  & Tingley, D. (2018). [The Civic Mission of MOOCs: Computational Measures of Engagement Across Differences in Online Courses](http://www.mikeyeomans.info/papers/EngagementAcrossDifference.pdf). International Journal of Artificial Intelligence in Education, 28(4), 553-589.

Yeomans, M., Kantor, A.  & Tingley, D. (2018). [Detecting Politeness in Natural Language](http://www.mikeyeomans.info/papers/Rpoliteness.pdf). The R Journal, 10(2), 489-502. [politeness R Package](https://cran.r-project.org/package=politeness)

***

## How can we build better relationships?

Yeomans, M. & Brooks, A.W. (2024). [Topic Preference Detection: A Conversational Approach to Perspective-Taking](http://www.mikeyeomans.info/papers/topic_selection.pdf). Invited Revisions.

Brooks, A.W. & Yeomans, M.(2024). [Boomerasking: Asking and then answering your own question](http://www.mikeyeomans.info/papers/topic_selection.pdf). Invited Revisions.

Huang, K., Yeomans, M., Brooks, A.W., Minson, J. & Gino, F. (2017). [It doesn't hurt to ask: Question-Asking increases liking](http://www.mikeyeomans.info/papers/question_asking.pdf). Journal of Personality and Social Psychology, 113(3), 430-452.

Yeomans, M., Brooks, A.W., Huang, K., Minson, J. & Gino, F. (2019). [It helps to ask: The cumulative benefits of asking follow-up questions. ](http://www.mikeyeomans.info/papers/cumulative.pdf). Journal of Personality and Social Psychology, 117(6), 1139-1144.

***

## How can we learn more from others?

Cho, J. Y., Tao, Y., Yeomans, M., Tingley, D., & Kizilcec, R. F. (2024, March). [Which Planning Tactics Predict Online Course Completion?](http://www.mikeyeomans.info/papers/plan_tactics.pdf). In Proceedings of the 14th Learning Analytics and Knowledge Conference, 360-370.

Blunden^, H., Kristal^, A., Whillans, A., Yoon, J., Burd, H., Bremner, G. & Yeomans, M. (2024). [Eliciting Advice Instead of Feedback Improves Developmental Input](http://www.mikeyeomans.info/papers/concreteness.pdf). Invited Revisions.

Yeomans, M. (2021). [A Concrete Application of Construct Construction for Natural Language Processing](http://www.mikeyeomans.info/papers/concreteness.pdf). Organizational Behavior and Human Decision Processes, 162, 81-94. [doc2concrete R package](https://cran.r-project.org/package=doc2concrete)

Kizilcec, R.^,  Reich, J.^, Yeomans, M.^, Dann, C., Brunskill, E., Lopez, G., Turkay, S., Williams, J. & Tingley, D. (2020). [Scaling Up Behavioral Science Interventions in Online Education](http://www.mikeyeomans.info/papers/earlyinterventions.pdf). Proceedings of the National Academy of Sciences, 117(26), 14900-14905

Yeomans, M., Shah, A., Mullainathan, S.  & Kleinberg, J. (2019). [Making Sense of Recommendations](http://www.mikeyeomans.info/papers/Making_Sense.pdf). Journal of Behavioral Decision Making, 32(4), 403-414.

Yeomans, M. (2019). [Some Hedonic Consequences of Perspective-Taking in Word of Mouth](http://www.mikeyeomans.info/papers/Advice_Supply.pdf). Journal of Consumer Psychology, 29(1), 22-38.

Yeomans, M.,Reich, J. (2017). [Planning to Learn: Planning Prompts Encourage and Forecast Goal Pursuit in Online Education](http://www.mikeyeomans.info/papers/planning.pdf). Proceedings of the Seventh International Conference on Learning Analytics  & Knowledge, 464-473. ACM.

Robinson, C., Yeomans, M.,Reich, J., Gelbach, H.  & Huileman, C. (2016). [Forecasting Student Achievement in MOOCs with Natural Language Processing](http://www.mikeyeomans.info/papers/utility_value.pdf). Proceedings of the Sixth International Conference on Learning Analytics  & Knowledge, 383-387. ACM.

***

## Field Experiments in Pro-Social Behaviour
(Not about conversation, but interesting nonetheless)

Yeomans, M.  & Al-Ubaydli, O. (2018). [How Does Fundraising Affect Charitable Giving? Evidence from a field experiment with volunteers](http://www.mikeyeomans.info/papers/Collateral_Effects_of_Fundraising.pdf). Journal of Economic Psychology, 64, 57-72.

Al-Ubaydli, O. & Yeomans, M. (2016). [Do people donate more when they perceive a single beneficiary whom they know? A field experimental test of the identifiability effect](http://www.mikeyeomans.info/papers/Identifiability_Effect.pdf). Journal of Behavioral and Experimental Economics, 66, 96-103.

Yeomans, M. & Herberich, D. (2014). [An experimental test of the effect of negative social norms on energy-efficient investments](http://www.mikeyeomans.info/papers/Tire_Pressure_Neglect.pdf). Journal of Economic Behavior & Organization, 108, 187-197.

***
