---
output:
  html_document: 
    toc: false
    toc_float: false
title: "Michael Yeomans"
---

<link rel="stylesheet" href="styles.css" type="text/css">
```{css, echo=FALSE}
.wdk_content-pagetitle {
display:none;
}
```

<div style="font-size: 20px">
I currently have two open-source R software packages available for the public (and third model in development, available for testing). They can be downloaded directly from CRAN. 

***

The politeness package uses sentence structure to extract stylistic markers from natural language. It relies on the SpaCy grammar parsing library in the background, so please make sure that is installed (using the spacyr R package) to get full use from this package.

Yeomans, M., Kantor, A.  & Tingley, D. (2018). [Detecting Politeness in Natural Language](http://www.mikeyeomans.info/papers/Rpoliteness.pdf). The R Journal, 10(2), 489-502. [politeness R Package](https://cran.r-project.org/package=politeness)

***

The doc2concrete package creates easy-to-use implementations of three models of concretneess. The associated journal article describes its formation, and also shows how many popular models of linguistic concreteness have little to no validity in domains - like advice and plan-making - where social context can change the meaning of what is said.


Yeomans, M. (2021). [A Concrete application of Construct Construction for Natural Language Processing](http://www.mikeyeomans.info/papers/concreteness.pdf). Organizational Behavior and Human Decision Processes, 162, 81-94. [doc2concrete R package](https://cran.r-project.org/package=doc2concrete)

***

The DICE package contains tools developed to measure two independent dimensions of conflict expressions - informational directness and relational intensity. The associated manuscript describes the formation of the NLP tool (the DICE-M), including benchmarks against other pre-trained models of conflict, and a corresponding human annotation guide (the DICE-H).

Yeomans, M., Bendersky, C., Weingart, L.R. & Kim, Y. (2024). [A Natural Language Processing Model for Conflict Expression in Conversation](https://github.com/myeomans/DICE). Under Review

***
